### ISSUE TITLE
Mejora Visualizer con nuevo campo de votante

### ISSUE THREAD

**Issue by Alebarmor** [angpomluz/Training_defensa_EGC#1]
Se va a añadir un nuevo campo de información para el votante que defina si este está desempleado o no. A su vez, también habrá de añadirse en el módulo la gráfica correspondiente, tal y como los otros campos de información tienen también, junto con sus correspondientes pruebas.

Soluciones propuestas:
- Se propone seguir el procedimiento realizado para los demás campos:
	1. Cargar un nuevo CSV con el nuevo campo de información generado
	2. Añadir al módulo Visualizer la adición de este campo y su correspondiente gráfica
	3. Crear los test correspondientes para verificar que la modificación funciona como se esperaba

---
**Autor incidencia**: Alejandro Barba Moreno
**Estado**:  Verified
**Prioridad**:  Medium
**Tipo**: Mejora
**Rol de encargado**: Programador

**Comment by juapormon** [comment]
Se ha añadido un nuevo campo al CSV que carga los datos mockeados, se ha adaptado el visualizer/views.py para que funcione con este cambio, se ha añadido una nueva gráfica a visualizer/templates/graficas.html y se ha hecho un test de selenium para comprobar que la funcionalidad esta implementada correctamente.
